### ISSUE TITLE
Topics for newsletter May 2021

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#2]

**Comment by vsoch** [comment]
It would be good to (by default) always include the last set of RSE Stories episodes. The last posting was in the February newsletter https://us-rse.org/2021-02-16-newsletter/#stories. So for this next one you could copy from February 18th to present! https://us-rse.org/rse-stories/archive/

**Comment by JeffCarver** [comment]
Please begin including a link to the most recent community call video. This can become a regular part of the newsletter

**Comment by JeffCarver** [comment]
Can we also include information about the Education & Training Working group? Some text like: 

US-RSE has formed a Working Group for those interested in regular discussions about Education & Training for RSEs with a goal of developing concrete deliverables. Some items that we consider as potential discussion topics for the group include: 1) identification of the types of training RSEs need, 2) gaps in current training offerings, 3) how training requirements may differ across domains, and 4) what role US-RSE can serve (including whether we should create some sort of US-RSE certificate). The Working Group meets the first Monday of the month at 1pm Eastern. If you are interested in joining the group, please contact Jeff Carver (carver@cs.ua.edu).

**Comment by danielskatz** [comment]
Please add
> **Special issue on software citation, indexing and discoverability** – Daniel S. Katz and Neil Chue Hong are editing a special issue of PeerJ CS on software citation, indexing and discoverability, so if you are doing any work in this area, please consider submitting it to this [special issue](https://peerj.com/special-issues/84-software).

**Comment by cferenba** [comment]
I'll add an announcement about the SC21 workshop - the call will likely open shortly after this newsletter comes out.
