### ISSUE TITLE
Topics for newsletter January 2022

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#6]

**Comment by NickleDave** [comment]
@sandragesing @danielskatz @cosden @lparsons here is that blurb about the SciPy BOF:

We plan to submit a proposal for a [Birds of a Feather session at SciPy 2022](https://www.scipy2022.scipy.org/bof-sessions) about US-RSE. It will be a moderated panel discussion. If you are interested in attending SciPy 2022 in Austin and representing US-RSE on the panel, please fill out this form: https://forms.gle/Mx4qW1zH518Ev2Cm6

Hope this is the right place to put this, please let me know if not

**Comment by NickleDave** [comment]
Also if there's any way you could put in a plug for the submissions it would be much appreciated! 🙏 
> [Submissions are also open](https://www.scipy2022.scipy.org/participate) for talks, posters, and tutorials at SciPy 2022, please consider submitting if you are an RSE working with Python in any capacity
