### ISSUE TITLE
Topics for newsletter February 2022

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#7]

**Comment by sandragesing** [comment]
From Chad Dougherty:
I propose adding this article to the "Interesting Reads" section of the next newsletter:
https://www.nature.com/articles/d41586-022-00217-0

**Comment by sandragesing** [comment]
From V:
I'm anticipating writing up the history post for the site at the end of the week, so I suspect it would be good to include in the February newsletter! We will also have a new RSE Stories released tomorow.

**Comment by crd477** [comment]
@danielskatz posted this one in Slack and I think it's also fit for inclusion in "Interesting Reads":
https://newscience.org/how-software-in-the-life-sciences-actually-works-and-doesnt-work/

**Comment by crd477** [comment]
Consider for inclusion in "Interesting Reads":
https://zerowithdot.com/improve-data-science-code/
although I expect that it's got less general appeal than the other articles mentioned already.

**Comment by danielskatz** [comment]
I think we should also consider https://www.catharsisinsight.com/reports (or https://www.catharsisinsight.com/_files/ugd/fce7f8_f9d2fea4f1b9478baeb7e84ab1b63759.pdf)

**Comment by mrmundt** [comment]
Adding from the Slack channel:

### Participants Needed for Mentorship Study

A team of software engineering researchers from Eindhoven University of Technology and Sandia National Laboratories are requesting participants to complete a short survey for their study on the role of mentorship for personal and professional development in software developers. [You can access the survey here!](https://docs.google.com/forms/d/e/1FAIpQLSdJ8pXrfzQaJQ2uXQX3cv3lLAlCm0h5n2YhWl-2Wq2BN66nWQ/viewform)

**Comment by NickleDave** [comment]
Next US-RSE DEI-WG Media Club:
We will be discussing the talk "Capability Maturity Model for Diversity in Organisations" by Rowland Mosbergen: https://www.youtube.com/watch?v=3pa5MkgEpWc 

Zoom link to register is here
https://emory.zoom.us/j/91646870292

**Comment by NickleDave** [comment]
@sandragesing one more, I almost forgot!
Could you add the SciPy BOF form please one more time?

> We plan to submit a proposal for a [Birds of a Feather session at SciPy 2022](https://www.scipy2022.scipy.org/bof-sessions) about US-RSE. It will be a moderated panel discussion. If you are interested in representing US-RSE on the panel, please fill out this form: https://forms.gle/Mx4qW1zH518Ev2Cm6. Note that the SciPy organizing committee has added options to participate virtually, so please consider joining and adding your voice to the BoF even if you are not attending the conference in person!

**Comment by danielskatz** [comment]
We should reuse any relevant news from ReSA's Feb newsletter: https://click.mlsend.com/link/c/YT0xODkyNTMzMTAzNjEyNjY0MzQ4JmM9aDJxMiZlPTAmYj05MjA4ODYxNzYmZD12N2g0cjJy.6S3BwSm3Sju16WzJFxw_d0NKLxma63raDheWjMdaAbA
