### ISSUE TITLE
Topics for newsletter March 2022

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#8]

**Comment by rcplane** [comment]
Hi @sandragesing , would the below make sense as an opportunity to add to the March newsletter? Thanks for any feedback. -Bennett

Seeking Public Climate Change AI Applications Ready to Scale 

Over the next few months I will be developing public workshop materials with the Cornell CAC ( https://cvw.cac.cornell.edu/topics ) for GPU cluster usage on large US NSF XSEDE resources. We would like to survey impactful climate application users to make sure their needs will be covered. I would appreciate any leads on research contacts for sample applications that are ready to run and can expect to highly utilize around 8-200 Nvidia V100 GPUs. Please see the link below for further details, we look forward to helping scale up climate impact!
https://community.climatechange.ai/c/grants-finding-collaborators/seeking-public-ccai-applications-ready-to-scale

**Comment by sandragesing** [comment]
This is a good topic for our community rubric. Maybe you can reformulate it in the third person as text to add to the newsletter? Thanks!

**Comment by jdamerow** [comment]
Hi @sandragesing,

if we could include the following in the newsletter that would be great!

---

The Code Review Working Group of [DHTech](https://dh-tech.github.io/) is starting the alpha phase of implementing a code review process for the digital humanities. For the initial round of reviews, we are looking for people willing to submit code for review and people willing to review someone else’s code. If you are willing to participate, we will also ask you to complete a feedback questionnaire at the end to help us improve the process. 

If you would like to have your code reviewed, please fill out the [code review request form](https://forms.gle/DKmsBSNsUY35nr6x9). Your code should be available on GitHub. It should take less than an hour to review. For more information about the conditions your code should meet, please review our [review preparation instructions](https://github.com/DHCodeReview/DHCodeReview/wiki/Authors:-Preparing-a-Code-Review).

If you are interested in being a reviewer, please fill out the [reviewer application form](https://forms.gle/PepxF6U64AT2Y5TZA). We expect reviews to take no more than an hour to complete. 

If you have any questions, feel free to get in touch with us either by joining the #code-review-wg channel on the [DHTech Slack](https://dh-tech.github.io/join/) or by emailing Julia Damerow (jdamerow@asu.edu).

**Comment by JeffCarver** [comment]
@sandragesing could you include this in the newsletter?

The US-RSE E&T Working Group is planning to offer a series of 2-3 hour hands-on training activities. We are looking for input on which topics are of most interest to the community. Please take just a minute or two to indicate your interest in a short list of topics here: https://universityofalabama.az1.qualtrics.com/jfe/form/SV_9RiNO94QQ72LCQK.
