### ISSUE TITLE
Topics for newsletter April 2022

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#9]

**Comment by mrmundt** [comment]
- RSE-eScience-2022 Workshop: Call for papers open - https://us-rse.org/rse-escience-2022/call/
- Applications for the Early Career Program at SC22 are open - https://sc22.supercomputing.org/submit/early-career-applications/

**Comment by NickleDave** [comment]
The next US-RSE DEI-WG Media Club will be Wed May 4 at 12pm EST. We'll discuss this Grace Hopper 2017 keynote from Mar Hicks:  
"Learning from History: Why Discrimination Against Women Destroyed the British Computing Industry, and Why We Should Care"
https://youtu.be/LjIISMOA40w

Link to register here:
https://emory.zoom.us/meeting/register/tJIqcu6vrT8sGN2Rsbc0W3-Zskdx5GsaKUN6

**Comment by mrmundt** [comment]
The next DiveRSE Event featuring Dr. Heather Turner speaking on "EDI in the R Community" will take place on May 4th, 2022. https://diverse-rse.github.io/events/2022-05-04
